# Linear regression - Medical Insurance

In [1]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

from sklearn.metrics import mean_squared_error,mean_absolute_error, r2_score

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("medical_insurance.csv")
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [6]:
df["sex"].value_counts()

male      676
female    662
Name: sex, dtype: int64

In [7]:
df["sex"].replace({'female':0,'male':1},inplace=True)

In [8]:
df['smoker'].value_counts()

no     1064
yes     274
Name: smoker, dtype: int64

In [9]:
df['smoker'].replace({'no':0,'yes':1},inplace=True)

In [10]:
df['region'].value_counts()

southeast    364
northwest    325
southwest    325
northeast    324
Name: region, dtype: int64

In [11]:
df = pd.get_dummies(df,columns=['region'])
df

age  sex     bmi  children  smoker      charges  region_northeast  \
0      19    0  27.900         0       1  16884.92400                 0   
1      18    1  33.770         1       0   1725.55230                 0   
2      28    1  33.000         3       0   4449.46200                 0   
3      33    1  22.705         0       0  21984.47061                 0   
4      32    1  28.880         0       0   3866.85520                 0   
...   ...  ...     ...       ...     ...          ...               ...   
1333   50    1  30.970         3       0  10600.54830                 0   
1334   18    0  31.920         0       0   2205.98080                 1   
1335   18    0  36.850         0       0   1629.83350                 0   
1336   21    0  25.800         0       0   2007.94500                 0   
1337   61    0  29.070         0       1  29141.36030                 0   

      region_northwest  region_southeast  region_southwest  
0                    0                 0                 1  
1                    0                 1                 0  
2                    0                 1                 0  
3                    1                 0                 0  
4                    1                 0                 0  
...                ...               ...               ...  
1333                 1                 0                 0  
1334                 0                 0                 0  
1335                 0                 1                 0  
1336                 0                 0                 1  
1337                 1                 0                 0  

[1338 rows x 10 columns]

In [12]:
df["children"].value_counts()

0    574
1    324
2    240
3    157
4     25
5     18
Name: children, dtype: int64

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   age               1338 non-null   int64  
 1   sex               1338 non-null   int64  
 2   bmi               1338 non-null   float64
 3   children          1338 non-null   int64  
 4   smoker            1338 non-null   int64  
 5   charges           1338 non-null   float64
 6   region_northeast  1338 non-null   uint8  
 7   region_northwest  1338 non-null   uint8  
 8   region_southeast  1338 non-null   uint8  
 9   region_southwest  1338 non-null   uint8  
dtypes: float64(2), int64(4), uint8(4)
memory usage: 68.1 KB


# Train Test Split

In [14]:
x = df.drop('charges',axis = 1)
y = df['charges']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=45)

In [15]:
x_train

age  sex     bmi  children  smoker  region_northeast  region_northwest  \
1075   32    0  29.590         1       0                 0                 0   
761    23    1  35.200         1       0                 0                 0   
6      46    0  33.440         1       0                 0                 0   
1171   43    0  26.700         2       1                 0                 0   
127    52    0  37.400         0       0                 0                 0   
...   ...  ...     ...       ...     ...               ...               ...   
580    59    1  25.460         1       0                 1                 0   
163    32    0  29.800         2       0                 0                 0   
607    59    0  23.655         0       1                 0                 1   
414    19    0  35.150         0       0                 0                 1   
971    34    0  23.560         0       0                 1                 0   

      region_southeast  region_southwest  
1075                 1                 0  
761                  0                 1  
6                    1                 0  
1171                 0                 1  
127                  0                 1  
...                ...               ...  
580                  0                 0  
163                  0                 1  
607                  0                 0  
414                  0                 0  
971                  0                 0  

[1070 rows x 9 columns]

# Model Training

In [16]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [17]:
# Testing data  Evaluation

y_pred = model.predict(x_test)

mse = mean_squared_error(y_test,y_pred)
print("MSE is :",mse)

rmse= np.sqrt(mse)
print("RMSE is :",rmse)

mae = mean_absolute_error(y_test,y_pred)
print("MAE is :",mae)


r2 = r2_score(y_test,y_pred)
print("R2 Score is :",r2)

MSE is : 38368288.57279199
RMSE is : 6194.21412067681
MAE is : 4435.096155453823
R2 Score is : 0.7035312341521323


In [18]:
# Training data  Evaluation

y_pred_train = model.predict(x_train)

mse = mean_squared_error(y_train,y_pred_train)
print("MSE is :",mse)

rmse= np.sqrt(mse)
print("RMSE is :",rmse)

mae = mean_absolute_error(y_train,y_pred_train)
print("MAE is :",mae)


r2 = r2_score(y_train,y_pred_train)
print("R2 Score is :",r2)

MSE is : 36112407.14310906
RMSE is : 6009.359961186305
MAE is : 4110.367959255667
R2 Score is : 0.7605646905517846


# Testing on Single row

In [21]:
x.head(1).T

0
age               19.0
sex                0.0
bmi               27.9
children           0.0
smoker             1.0
region_northeast   0.0
region_northwest   0.0
region_southeast   0.0
region_southwest   1.0

In [58]:
age = 39
sex ='male'
bmi = 10.5
children = 3
smoker  = 'yes'
region = 'southwest'

#charges = ?

In [22]:
column_names = x.columns
column_names

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region_northeast',
       'region_northwest', 'region_southeast', 'region_southwest'],
      dtype='object')

In [24]:
test_array = np.zeros(len(x.columns))
test_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
test_array[0] = age
test_array[1] = label_encoded_data["sex"][sex]
test_array[2] = bmi
test_array[3] = children
test_array[4] = label_encoded_data['smoker'][smoker]
#test_array[5] = region


In [47]:
label_encoded_data = {"sex":{'female':0,'male':1},
                      'smoker':{'no':0,'yes':1}
                     }

label_encoded_data['smoker'][smoker]
label_encoded_data["sex"][sex]

0

In [48]:
region = "region_" + region
region

'region_southwest'

In [55]:
region_index = np.where(column_names == region )[0][0]
region_index

8

In [66]:
test_array[0] = age
test_array[1] = label_encoded_data["sex"][sex]
test_array[2] = bmi
test_array[3] = children
test_array[4] = label_encoded_data['smoker'][smoker]
test_array[region_index] = 1

In [67]:
test_array

array([40. ,  0. , 26.5,  3. ,  0. ,  0. ,  0. ,  0. ,  1. ])

In [64]:
age = 26
sex ='female'
bmi = 26.5
children = 3
smoker  = 'no'
region = 'southwest'

In [68]:
model.predict([test_array])

array([7832.03873491])

In [69]:
import pickle
with open ("Linear_model.pkl","wb") as f:
    pickle.dump(model,f)

In [70]:
project_data = {"sex":{'female':0,'male':1},
                      'smoker':{'no':0,'yes':1},
                      'columns' :list(x.columns)
                     }

In [71]:
import json

with open("Project_data.json","w") as f:
    json.dump(project_data,f)